spring:
  application:
    name: hotchpotch

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.222.242:6066/hotchpotch?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: a1b2c3#


  redis:
    host: 47.99.222.242
    port: 6379
    password: nideshengri
    database: 6
    timeout: 3s
    lettuce:
      pool:
        max-wait: 5s
        min-idle: 1
        time-between-eviction-runs: 5m

  data:
    redis:
      host: 47.99.222.242
      port: 6379
      password: nideshengri
      database: 7
      timeout: 3s

  mvc:
   path-matching:
    matching-strategy: ant_path_matcher

server:
  port: 8080


# jwt 配置
jwt:
  # 加密盐
  secret: hotchpotch
  # access_token过期时间(ms)
  access-token-expiration-date: 300000
  # refresh_token过期时间(ms)
  refresh-token-expiration-date: 600000


mybatis-plus:
  type-aliases-package: com.yuanliubei.hotchpotch.model.domain
  type-aliases-super-type: com.yuanliubei.hotchpotch.model.domain.BaseEntity
  mapper-locations:
    - classpath:/mapper/**.xml

  configuration:
    map-underscore-to-camel-case: true

  global-config:
    banner: false
    db-config:
      id-type: NONE # 无特定生成策略，如果全局配置中有 IdType 相关的配置，则会跟随全局配置。
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
