spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:6066/ai_temp_debug?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: a1b2c3#
    driver-class-name: com.mysql.cj.jdbc.Driver